name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to carsApp directory and list contents
        run: |
          cd carsApp
          pwd
          ls -al

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
        # No working-directory here, the 'cd' command handles it in shell steps.

      - name: Set up database schema
        run: |
          cd carsApp
          bundle exec rails db:schema:load

      - name: Run tests
        run: |
          cd carsApp
          bundle exec rails test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to carsApp directory and list contents
        run: |
          cd carsApp
          pwd
          ls -al

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Lint code
        run: |
          cd carsApp
          bundle exec rubocop
