name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Gemfile presence
        run: ls -la
        working-directory: ./carsApp

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
        working-directory: ./carsApp

      - name: Set up database schema
        run: bundle exec rails db:schema:load
        working-directory: ./carsApp

      - name: Run tests
        run: bundle exec rails test
        working-directory: ./carsApp

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Run RuboCop linter
        run: bundle exec rubocop
        working-directory: ./carsApp